package controller;

public enum Event {
	ADD_WORD_ADMIN_OPTION, ADD_WORD, SPA_TO_ENG_BTN, BACK_BTN, SEARCH_ENG_WORD, SEARCH_FRN_WORD, SPA_TO_FRN_BTN, EXIT_BTN, CANCEL_ADD_OR_DELETE_WORD, DELETE_WORD, DELETE_WORD_ADMIN_OPTION
}
